# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1McvwpgE9iLh8_R0kYK5QREWZAg3p5uMj
"""

import os
os.environ["GROQ_API_KEY"] = "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"
os.environ["HF_TOKEN"] = "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"

import os
import json
import requests
import urllib.parse
import numpy as np
from io import BytesIO
from groq import Groq
from PIL import Image, ImageDraw, ImageFont, ImageFilter, ImageEnhance, ImageChops
import time
import base64
from flask import Flask, request, jsonify
from flask_cors import CORS

# ─────────────────────────────────────────────
# YAPILANDIRMA
# ─────────────────────────────────────────────
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")
groq_client = Groq(api_key=GROQ_API_KEY)

app = Flask(__name__)
CORS(app)

URUN_SABLONLARI = {
    "vazo":   "plain white ceramic tall vase, centered, solid pure black background, no shadows, studio lighting, photorealistic 8K",
    "tabak":  "plain white ceramic plate, centered, solid pure black background, no shadows, studio lighting, photorealistic 8K",
    "bardak": "plain white ceramic mug with handle, centered, solid pure black background, no shadows, studio lighting, photorealistic 8K",
    "comlek": "plain white clay pot with lid, centered, solid pure black background, no shadows, studio lighting, photorealistic 8K",
    "kilim":  "plain beige kilim rug flat lay, centered, solid pure black background, no shadows, soft lighting, photorealistic 8K",
}

URUN_PROMPT_EKLER = {
    "vazo":   "highly detailed handmade Cappadocia tall vase intricate hand-painted patterns terracotta texture Anatolian craftmanship white background photorealistic 8K",
    "tabak":  "highly detailed handmade Cappadocia ceramic plate intricate hand-painted patterns white background photorealistic 8K",
    "bardak": "highly detailed handmade Cappadocia ceramic mug intricate hand-painted patterns white background photorealistic 8K",
    "comlek": "highly detailed handmade Cappadocia clay pot intricate hand-painted patterns white background photorealistic 8K",
    "kilim":  "highly detailed traditional Cappadocia kilim rug geometric patterns wool texture aerial view photorealistic 8K",
}


# ─────────────────────────────────────────────
# 1. İSTEK ANALİZİ
# ─────────────────────────────────────────────
def istek_analiz_et(kullanici_istegi):
    yanit = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        response_format={"type": "json_object"},
        messages=[
            {
                "role": "system",
                "content": """Kullanıcının isteğini analiz et ve JSON formatında döndür:
{
  "metin": "ürüne yazılacak metin varsa yaz, yoksa null",
  "metin_konum": "orta, sol_ust, sag_ust, sol_alt, sag_alt, ust, alt — belirtilmemişse orta",
  "urun_tipi": "vazo, tabak, bardak, comlek veya kilim — belirtilmemişse vazo",
  "kultur": "ülke/kültür varsa Türkçe küçük harfle, yoksa null",
  "desen": "tasarım isteği"
}
Sadece JSON yaz."""
            },
            {"role": "user", "content": kullanici_istegi}
        ]
    )
    return json.loads(yanit.choices[0].message.content)


# ─────────────────────────────────────────────
# 2. GÖRSEL ÜRETİMİ
# ─────────────────────────────────────────────
def gorsel_uret(prompt, genislik=512, yukseklik=768, max_deneme=4):
    clean = prompt.encode('ascii', 'ignore').decode('ascii')
    clean = ' '.join(clean.split())[:500]
    encoded = urllib.parse.quote(clean)

    for deneme in range(max_deneme):
        try:
            print(f"  Görsel üretiliyor... (deneme {deneme + 1}/{max_deneme})")
            seed = int(time.time()) + deneme
            url = (
                f"https://image.pollinations.ai/prompt/{encoded}"
                f"?width={genislik}&height={yukseklik}&nologo=true&model=flux&seed={seed}"
            )
            r = requests.get(url, timeout=120)
            if r.status_code == 200 and "image" in r.headers.get("content-type", ""):
                img = Image.open(BytesIO(r.content))
                if img.size[0] > 10:
                    print(f"  Görsel üretildi: {img.size}")
                    return img
            time.sleep(5)
        except Exception as e:
            print(f"  Hata: {e}")
            time.sleep(6)

    fallback = Image.new('RGB', (genislik, yukseklik), (10, 10, 10))
    return fallback


# ─────────────────────────────────────────────
# 3. OTOMATİK EŞİK MASKESI
#    Görselin köşe piksellerinden arka plan
#    rengini otomatik öğrenir → daha güvenilir
# ─────────────────────────────────────────────
def vazo_maskesi_olustur(vazo_img):
    rgb = vazo_img.convert("RGB")
    arr = np.array(rgb, dtype=np.float32)
    h, w = arr.shape[:2]

    # Köşe piksellerinden arka plan rengini öğren
    koseler = np.array([
        arr[0, 0], arr[0, w-1],
        arr[h-1, 0], arr[h-1, w-1],
        arr[0, w//2], arr[h//2, 0],
        arr[h//2, w-1], arr[h-1, w//2],
    ])
    arkaplan_rengi = np.median(koseler, axis=0)  # [R, G, B]
    print(f"  Arka plan rengi (medyan): {arkaplan_rengi}")

    # Piksel başına arka plan renginden uzaklık (Öklid mesafesi)
    r, g, b = arr[:,:,0], arr[:,:,1], arr[:,:,2]
    mesafe = np.sqrt(
        (r - arkaplan_rengi[0])**2 +
        (g - arkaplan_rengi[1])**2 +
        (b - arkaplan_rengi[2])**2
    )

    # Eşik: arka plana benzeyen pikseller = 0 (siyah), ürün = 255 (beyaz)
    # Eşik değerini dinamik ayarla: arka plan ne kadar koyu/tek renkse eşik düşük olsun
    esik = max(30, np.percentile(mesafe, 15))
    print(f"  Maske eşiği: {esik:.1f}")

    maske = np.where(mesafe < esik, 0, 255).astype(np.uint8)

    maske_img = Image.fromarray(maske, mode='L')

    # Morfoloji: küçük delikleri kapat, kenarları temizle
    maske_img = maske_img.filter(ImageFilter.MaxFilter(9))   # delikleri doldur
    maske_img = maske_img.filter(ImageFilter.MinFilter(5))   # taşan kenarları geri çek
    maske_img = maske_img.filter(ImageFilter.GaussianBlur(radius=3))  # yumuşat

    return maske_img


# ─────────────────────────────────────────────
# 4. DESENE SARMA
# ─────────────────────────────────────────────
def deseni_vazoya_sar(vazo_img, desen_img, opaklık=0.80):
    w, h = vazo_img.size
    vazo_rgb = vazo_img.convert("RGB")
    desen = desen_img.convert("RGB").resize((w, h), Image.LANCZOS)

    # Maske
    maske = vazo_maskesi_olustur(vazo_rgb)

    # Vazo aydınlatma haritası (gri ton)
    vazo_gray = vazo_rgb.convert("L")
    vazo_gray_rgb = Image.merge("RGB", [vazo_gray, vazo_gray, vazo_gray])

    # Multiply blend: desen × aydınlatma → 3D görünüm
    blended = ImageChops.multiply(desen, vazo_gray_rgb)
    blended = ImageEnhance.Brightness(blended).enhance(2.0)
    blended = ImageEnhance.Color(blended).enhance(1.5)

    # Opaklık karışımı
    final_desen = Image.blend(vazo_rgb, blended, opaklık)

    # Maske uygula: vazo bölgesi → desen, dışı → beyaz
    beyaz = Image.new("RGB", (w, h), (255, 255, 255))
    sonuc = Image.composite(final_desen, beyaz, maske)
    sonuc = ImageEnhance.Contrast(sonuc).enhance(1.1)
    return sonuc


# ─────────────────────────────────────────────
# 5. METİN EKLEME
# ─────────────────────────────────────────────
def metni_ekle(gorsel, metin, konum="orta"):
    img = gorsel.copy().convert("RGBA")
    w, h = img.size
    font_size = max(40, int(h * 0.075))

    font = None
    for yol in [
        "/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    ]:
        try:
            font = ImageFont.truetype(yol, font_size)
            break
        except Exception:
            continue
    if font is None:
        font = ImageFont.load_default()

    dummy = ImageDraw.Draw(img)
    try:
        bbox = dummy.textbbox((0, 0), metin, font=font)
        text_w, text_h = bbox[2] - bbox[0], bbox[3] - bbox[1]
    except Exception:
        text_w, text_h = len(metin) * 20, 40

    konumlar = {
        "orta":    ((w - text_w) // 2, (h - text_h) // 2),
        "ust":     ((w - text_w) // 2, int(h * 0.12)),
        "alt":     ((w - text_w) // 2, h - text_h - int(h * 0.12)),
        "sol_ust": (int(w * 0.08), int(h * 0.12)),
        "sag_ust": (w - text_w - int(w * 0.08), int(h * 0.12)),
        "sol_alt": (int(w * 0.08), h - text_h - int(h * 0.12)),
        "sag_alt": (w - text_w - int(w * 0.08), h - text_h - int(h * 0.12)),
    }
    x, y = konumlar.get(konum, konumlar["orta"])

    golge = Image.new("RGBA", img.size, (0, 0, 0, 0))
    ImageDraw.Draw(golge).text((x + 3, y + 3), metin, font=font, fill=(20, 10, 5, 90))
    golge = golge.filter(ImageFilter.GaussianBlur(radius=2.5))

    boya = Image.new("RGBA", img.size, (0, 0, 0, 0))
    bd = ImageDraw.Draw(boya)
    for ox, oy, renk in [
        (-1, 0, (15, 30, 100, 80)),
        (1,  0, (15, 30, 100, 80)),
        (0, -1, (15, 30, 100, 80)),
        (0,  1, (15, 30, 100, 80)),
        (0,  0, (30, 50, 140, 210)),
    ]:
        bd.text((x + ox, y + oy), metin, font=font, fill=renk)
    boya = boya.filter(ImageFilter.GaussianBlur(radius=0.6))

    kabartma = Image.new("RGBA", img.size, (0, 0, 0, 0))
    ImageDraw.Draw(kabartma).text((x - 1, y - 1), metin, font=font, fill=(255, 255, 240, 40))

    sonuc = Image.alpha_composite(img, golge)
    sonuc = Image.alpha_composite(sonuc, boya)
    sonuc = Image.alpha_composite(sonuc, kabartma)
    return sonuc.convert("RGB")


# ─────────────────────────────────────────────
# 6. GÖRSEL → BASE64
# ─────────────────────────────────────────────
def gorsel_to_base64(gorsel):
    buffer = BytesIO()
    gorsel.save(buffer, format="PNG")
    buffer.seek(0)
    return base64.b64encode(buffer.read()).decode("utf-8")


# ─────────────────────────────────────────────
# 7. ANA ÜRETİM FONKSİYONU
# ─────────────────────────────────────────────
def urun_uret(kullanici_istegi, fotograf_yolu=None, debug=False):
    print("=" * 50)
    print("İstek analiz ediliyor...")
    analiz = istek_analiz_et(kullanici_istegi)
    print(f"Analiz: {analiz}")
    print("=" * 50)

    urun_tipi = analiz.get("urun_tipi", "vazo")

    if fotograf_yolu:
        print(f"[1/3] '{urun_tipi}' üretiliyor (siyah arka plan)...")
        vazo_img = gorsel_uret(URUN_SABLONLARI[urun_tipi])

        if debug:
            vazo_img.save("/tmp/vazo_ham.png")
            print("  [DEBUG] Ham vazo: /tmp/vazo_ham.png")
            maske_debug = vazo_maskesi_olustur(vazo_img.convert("RGB"))
            maske_debug.save("/tmp/maske_debug.png")
            print("  [DEBUG] Maske: /tmp/maske_debug.png")

        print("[2/3] Desen uygulanıyor...")
        desen_img = Image.open(fotograf_yolu).convert("RGB")
        gorsel = deseni_vazoya_sar(vazo_img, desen_img)
        print("[3/3] Tamamlandı!")
    else:
        print("[1/1] Prompt ile görsel üretiliyor...")
        ek = URUN_PROMPT_EKLER.get(urun_tipi, "")
        kultur = analiz.get("kultur", "")
        kultur_eki = f"{kultur} style" if kultur else ""
        prompt = f"{ek}, {kultur_eki}, {analiz.get('desen', '')}".strip(", ")
        gorsel = gorsel_uret(prompt)

    if analiz.get("metin"):
        gorsel = metni_ekle(gorsel, analiz["metin"], analiz.get("metin_konum", "orta"))

    print("=" * 50)
    return gorsel


def gorseli_kaydet(gorsel, dosya_adi="sonuc.png"):
    gorsel.save(dosya_adi, format="PNG", optimize=True)
    print(f"Kaydedildi: {dosya_adi}")
    return dosya_adi


# ─────────────────────────────────────────────
# 8. FLASK API
# ─────────────────────────────────────────────
@app.route("/uret", methods=["POST"])
def uret():
    """
    POST /uret
    Form-data:
        istek    : str  (zorunlu)
        fotograf : file (opsiyonel)
    Yanıt:
        { basarili, gorsel_base64, analiz }
    """
    try:
        istek_metni = request.form.get("istek", "").strip()
        if not istek_metni:
            return jsonify({"basarili": False, "hata": "istek alanı boş"}), 400

        analiz = istek_analiz_et(istek_metni)
        urun_tipi = analiz.get("urun_tipi", "vazo")

        fotograf_yolu = None
        if "fotograf" in request.files:
            dosya = request.files["fotograf"]
            if dosya.filename:
                fotograf_yolu = f"/tmp/{int(time.time())}_{dosya.filename}"
                dosya.save(fotograf_yolu)

        if fotograf_yolu:
            vazo_img = gorsel_uret(URUN_SABLONLARI[urun_tipi])
            desen_img = Image.open(fotograf_yolu).convert("RGB")
            gorsel = deseni_vazoya_sar(vazo_img, desen_img)
        else:
            ek = URUN_PROMPT_EKLER.get(urun_tipi, "")
            kultur = analiz.get("kultur", "")
            kultur_eki = f"{kultur} style" if kultur else ""
            prompt = f"{ek}, {kultur_eki}, {analiz.get('desen', '')}".strip(", ")
            gorsel = gorsel_uret(prompt)

        if analiz.get("metin"):
            gorsel = metni_ekle(gorsel, analiz["metin"], analiz.get("metin_konum", "orta"))

        return jsonify({
            "basarili": True,
            "gorsel_base64": gorsel_to_base64(gorsel),
            "analiz": analiz,
        })

    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({"basarili": False, "hata": str(e)}), 500


@app.route("/saglik", methods=["GET"])
def saglik():
    return jsonify({"durum": "çalışıyor"})


if __name__ == "__main__":
    print("KapadokyaCraft API başlatılıyor...")
    print("Endpoint: POST http://localhost:5000/uret")
    app.run(host="0.0.0.0", port=5000, debug=False)
    #-------------------------------------------------------------------------
# Mevcut kodun ALTINA ekle:

# ─────────────────────────────────────────────
# 9. TASARIM OTURUMU YÖNETİMİ
# ─────────────────────────────────────────────
tasarim_oturumlari = {}  # session_id -> {tasarim_gecmisi, son_gorsel, prompt_gecmisi}

@app.route("/tasarim/baslat", methods=["POST"])
def tasarim_baslat():
    """Yeni tasarım oturumu başlatır"""
    try:
        data = request.json
        kullanici_prompt = data.get("prompt", "")
        urun_tipi = data.get("urun_tipi", "vazo")

        # Benzersiz oturum ID
        session_id = base64.b64encode(os.urandom(16)).decode('utf-8')[:16]

        # Yeni tasarım oluştur
        analiz = istek_analiz_et(kullanici_prompt)
        analiz["urun_tipi"] = urun_tipi

        ek = URUN_PROMPT_EKLER.get(urun_tipi, "")
        prompt = f"{ek}, {analiz.get('desen', '')}"
        gorsel = gorsel_uret(prompt)

        if analiz.get("metin"):
            gorsel = metni_ekle(gorsel, analiz["metin"], analiz.get("metin_konum", "orta"))

        # Oturumu kaydet
        tasarim_oturumlari[session_id] = {
            "son_gorsel": gorsel,
            "tasarim_gecmisi": [gorsel],
            "prompt_gecmisi": [kullanici_prompt],
            "urun_tipi": urun_tipi,
            "analiz": analiz
        }

        return jsonify({
            "basarili": True,
            "session_id": session_id,
            "gorsel_base64": gorsel_to_base64(gorsel),
            "analiz": analiz
        })

    except Exception as e:
        return jsonify({"basarili": False, "hata": str(e)}), 500


@app.route("/tasarim/duzenle", methods=["POST"])
def tasarim_duzenle():
    """Mevcut tasarımı kullanıcının isteğine göre düzenler"""
    try:
        data = request.json
        session_id = data.get("session_id")
        duzenleme_istegi = data.get("duzenleme", "")  # "çiçekleri büyüt", "renkleri koyulaştır" vb.

        if session_id not in tasarim_oturumlari:
            return jsonify({"basarili": False, "hata": "Oturum bulunamadı"}), 404

        oturum = tasarim_oturumlari[session_id]
        onceki_prompt = oturum["prompt_gecmisi"][-1]

        # Düzenleme promptu oluştur
        yeni_prompt = f"{onceki_prompt}, ancak {duzenleme_istegi}"

        # Yeni görsel üret
        analiz = istek_analiz_et(yeni_prompt)
        ek = URUN_PROMPT_EKLER.get(oturum["urun_tipi"], "")
        prompt = f"{ek}, {analiz.get('desen', '')}"
        gorsel = gorsel_uret(prompt)

        if analiz.get("metin"):
            gorsel = metni_ekle(gorsel, analiz["metin"], analiz.get("metin_konum", "orta"))

        # Oturumu güncelle
        oturum["son_gorsel"] = gorsel
        oturum["tasarim_gecmisi"].append(gorsel)
        oturum["prompt_gecmisi"].append(yeni_prompt)

        return jsonify({
            "basarili": True,
            "gorsel_base64": gorsel_to_base64(gorsel),
            "analiz": analiz
        })

    except Exception as e:
        return jsonify({"basarili": False, "hata": str(e)}), 500


@app.route("/tasarim/fotograf_ekle", methods=["POST"])
def tasarim_fotograf_ekle():
    """Kullanıcının yüklediği fotoğrafı ürüne uygular"""
    try:
        session_id = request.form.get("session_id")
        dosya = request.files.get("fotograf")

        if not dosya:
            return jsonify({"basarili": False, "hata": "Fotoğraf gerekli"}), 400

        if session_id not in tasarim_oturumlari:
            return jsonify({"basarili": False, "hata": "Oturum bulunamadı"}), 404

        # Fotoğrafı geçici kaydet
        fotograf_yolu = f"/tmp/{int(time.time())}_{dosya.filename}"
        dosya.save(fotograf_yolu)

        oturum = tasarim_oturumlari[session_id]
        urun_tipi = oturum["urun_tipi"]

        # Ürün şablonu oluştur
        urun_img = gorsel_uret(URUN_SABLONLARI[urun_tipi])

        # Deseni uygula
        desen_img = Image.open(fotograf_yolu).convert("RGB")
        gorsel = deseni_vazoya_sar(urun_img, desen_img)

        # Metin varsa ekle
        if oturum["analiz"].get("metin"):
            gorsel = metni_ekle(gorsel, oturum["analiz"]["metin"],
                               oturum["analiz"].get("metin_konum", "orta"))

        # Oturumu güncelle
        oturum["son_gorsel"] = gorsel
        oturum["tasarim_gecmisi"].append(gorsel)

        # Geçici dosyayı temizle
        os.remove(fotograf_yolu)

        return jsonify({
            "basarili": True,
            "gorsel_base64": gorsel_to_base64(gorsel)
        })

    except Exception as e:
        return jsonify({"basarili": False, "hata": str(e)}), 500


@app.route("/tasarim/gerial", methods=["POST"])
def tasarim_gerial():
    """Son değişikliği geri alır"""
    try:
        session_id = request.json.get("session_id")

        if session_id not in tasarim_oturumlari:
            return jsonify({"basarili": False, "hata": "Oturum bulunamadı"}), 404

        oturum = tasarim_oturumlari[session_id]

        if len(oturum["tasarim_gecmisi"]) > 1:
            oturum["tasarim_gecmisi"].pop()  # Sonuncuyu sil
            oturum["prompt_gecmisi"].pop() if oturum["prompt_gecmisi"] else None
            oturum["son_gorsel"] = oturum["tasarim_gecmisi"][-1]

            return jsonify({
                "basarili": True,
                "gorsel_base64": gorsel_to_base64(oturum["son_gorsel"])
            })
        else:
            return jsonify({"basarili": False, "hata": "Geri alınacak değişiklik yok"}), 400

    except Exception as e:
        return jsonify({"basarili": False, "hata": str(e)}), 500


@app.route("/tasarim/kaydet", methods=["POST"])
def tasarim_kaydet():
    """Tasarımı kalıcı olarak kaydeder"""
    try:
        session_id = request.json.get("session_id")
        dosya_adi = request.json.get("dosya_adi", "tasarim.png")

        if session_id not in tasarim_oturumlari:
            return jsonify({"basarili": False, "hata": "Oturum bulunamadı"}), 404

        oturum = tasarim_oturumlari[session_id]
        gorsel = oturum["son_gorsel"]

        # Kalıcı kaydet
        kayit_yolu = f"/tmp/son_tasarimlar/{session_id}_{dosya_adi}"
        os.makedirs("/tmp/son_tasarimlar", exist_ok=True)
        gorsel.save(kayit_yolu)

        return jsonify({
            "basarili": True,
            "dosya_yolu": kayit_yolu,
            "mesaj": "Tasarım kaydedildi"
        })

    except Exception as e:
        return jsonify({"basarili": False, "hata": str(e)}), 500